version: "3.9"

services:
  indexer:
    restart: "no"
    build:
      dockerfile: Dockerfile
    user: cosmos-indexer
    stop_grace_period: 10s
    networks:
      default:
        aliases:
          - cosmos-indexer
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EXTENDED_ARGS=""
      - LOG_LEVEL="info"
    command:
    - /bin/sh
    - -c
    - |
      cosmos-indexer index \
      --log.pretty=${PRETTY_LOG} \
      --log.level=${LOG_LEVEL} \
      --base.index-transactions=${INDEX_TRANSACTIONS} \
      --base.index-block-events=${INDEX_BLOCK_EVENTS} \
      --base.start-block=${START_BLOCK} \
      --base.end-block=${END_BLOCK} \
      --base.throttling=${THROTTLING} \
      --base.rpc-workers=${RPC_WORKERS} \
      --base.reindex=${REINDEX} \
      --base.reattempt-failed-blocks=false \
      --probe.rpc=${RPC_URL} \
      --probe.account-prefix=${ACCOUNT_PREFIX} \
      --probe.chain-id=${CHAIN_ID} \
      --probe.chain-name=${CHAIN_NAME} \
      --database.host=${POSTGRES_HOST} \
      --database.port=${POSTGRES_PORT} \
      --database.database=${POSTGRES_DB} \
      --database.user=${POSTGRES_USER} \
      --database.password=${POSTGRES_PASSWORD} \
      ${EXTENDED_ARGS}

networks:
  default:
